version: '3'
services:
  ganache:
     image: ganache-cli
     build: ./ganache-cli
     container_name: ganache
     restart: always
     ports:
      - "8545:8545"
  client:
    image: webapp
    build: ./client
    depends_on:
       - ganache
    container_name: webapp
    restart: always
    ports:
      - "80:3000"
  mariadb:
    image: mariadb
    build: ./mysql
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    command: bash -c "mysql -u root -p$MYSQL_ROOT_PASSWORD  -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'redhat';FLUSH PRIVILEGES;" && \
            mysql -u root -p${MYSQL_ROOT_PASSWORD}  < /tmp/bitcoin.sql && mysql -u root -p${MYSQL_ROOT_PASSWORD}  < /tmp/property.sql"
    ports:
      - "3306:3306"
volumes:
    mariadb:
      driver: local
