version: '3'
services:
  ganache:
     image: ganache-cli
     build: ./ganache-cli
     container_name: ganache
     restart: always
     ports:
      - "8545:8545"
  client:
    image: webapp
    build: ./client
    depends_on:
       - ganache
    container_name: webapp
    restart: always
    ports:
      - "80:3000"
  mariadb:
    image: mysql
    container_name: mysql
    volumes:
      - ./mysql:/sql/
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=bitcoin
      - MYSQL_DATABASE=property
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
volumes:
    mariadb:
      driver: local
