version: '3'
services:
  ganache:
     image: ganache-cli
     build: ./ganache-cli
     container_name: ganache
     restart: always
     
  client:
    image: webapp
    build: ./client
    depends_on:
       - ganache
    container_name: webapp
    restart: always
    ports:
      - "80:3000"
