version: '3'
services:
  ganache:
     image: ganache-cli
     build: ./ganache-cli
     container_name: ganache
     restart: always
     ports:
      - "8545:8545"
  client:
    image: webapp
    build: ./client
    depends_on:
       - ganache
    container_name: webapp
    restart: always
    ports:
      - "80:3000"
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
    volume-name: mariadb
    driver: local
