version: '3'
services:
  ganache:
     image: ganache-cli
     build: ./ganache-cli
     container_name: ganache
     restart: always
     ports:
      - "8545:8545"
  client:
    image: webapp
    build: ./client
    depends_on:
       - ganache
    container_name: webapp
    restart: always
    ports:
      - "80:3000"
  dcert:
    image: dcert
    build: ./digital-certificate
    container_name: dcert
    restart: always
    volumes:
      - digitalcertificate:/app/certificates
    ports:
      - "8080:80"
  server:
    image: server
    build: ./server
    container_name: server
    restart: always
    volumes:
      - digitalcertificate:/app/certificates
    ports:
      - "8000:80"
volumes:
    mariadb:
      driver: local
    digitalcertificate:
      driver: local
